---
# Headless Service.
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  # name: {{ .Values.service.name }}
  labels:
    app: {{ .Release.Name }}
    # app: {{ .Values.mongodb.labels.app }}
spec:
  clusterIP: None
  selector:
      app: {{ .Release.Name }}
      # app: {{ .Values.mongodb.labels.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
---