---
service:
  name: mysql
  port: 3306
  targetPort: 3306

storage:
  name: mysql-data
  size: 1Gi
  mountPath: /var/lib/mysql
  hostPath: /backup-mysql
  className: sc-for-kind
  reclaimPolicy: Delete
  bindingMode: WaitForFirstConsumer
  accessMode: ReadWriteOnce

replicaCount: 1

container:
  name: mysql-container
  containerPort: 3306

image:
  repository: sivaram0101/mysql-roboshop
  tag: v1
  pullPolicy: IfNotPresent

env:
- name: MYSQL_DATABASE
  value: cities
- name: MYSQL_USER
  value: shipping
- name: MYSQL_PASSWORD
  value: RoboShop@1
- name: MYSQL_ROOT_PASSWORD
  value: RoboShop@1
---