replicaCount: 1

image:
  repository: sivaram0101/mongodb-roboshop
  tag: v1
  pullPolicy: IfNotPresent

container:
  port: 27017
  name: mongodb-container

service:
  name: mongodb
  port: 27017
  targetPort: 27017

storage:
  className: roboshop-sc
  size: 1Gi
  hostPath: /backup/mongodb

mongodb:
  labels:
    app: mongodb-roboshop
